# Generated by Django 5.0.6 on 2024-05-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dauGiaApi', '0004_alter_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='minPrice',
            field=models.IntegerField(default=0),
        ),
    ]
